// outcomes：その依頼で起こりうる結末の候補（2026-08-01・段階①でコードからここへ移した）。
// 完遂（full）／部分（partial）／未達（fail）の3段階で持つ。工程エンジンの結果の段階と同じ形なので、
// 結末と段階の対応表を別に持たなくてよい（app.js の GROWTH_TIER_BY_RESULT はここから作られる）。
// fail が空の依頼は、未達のとき共通の「引き返し」に落ちる。
// 並び順は移行前のコードのままにしてある（同じ乱数で同じ結末になるため）。
window.masterQuests = [
  {
    id: "quest_herb",
    title: "森の薬草採集",
    category: "探索",
    danger: "低",
    area: "薄明の森",
    durationBand: "short_1h",
    unlockedBy: "quest_signpost",
    recommended: ["斥候", "薬草師"],
    tags: ["探索", "採集", "観察"],
    observationTarget: "森喰い兎",
    tensionBase: 25,
    tensionRange: 20,
    summary: "森の浅い場所で薬草を採集する。小型の獣による荷荒らしが報告されている。",
    outcomes: { full: ["成功", "採集優先", "観察優先"], partial: ["小成功"], fail: [] }
  },
  {
    id: "quest_signpost",
    title: "古い道標の確認",
    category: "探索",
    danger: "低",
    area: "古い街道",
    durationBand: "short_30m",
    unlockedBy: "quest_old_house_cleanup",
    recommended: ["斥候"],
    tags: ["探索", "街道", "記録"],
    observationTarget: "なし",
    tensionBase: 18,
    tensionRange: 16,
    summary: "雨で傾いた道標を確認し、街道記録と照合する。戦闘は想定されていない。",
    outcomes: { full: ["成功"], partial: ["応急処置", "照合保留", "再確認"], fail: [] }
  },
  {
    id: "quest_letter",
    title: "届けられなかった手紙",
    category: "生活",
    danger: "低",
    area: "雨待ちの街道",
    durationBand: "short_1h",
    unlockedBy: "quest_herb_delivery",
    recommended: ["慎重", "郵便配達人"],
    tags: ["生活", "配達", "記録"],
    observationTarget: "なし",
    tensionBase: 16,
    tensionRange: 14,
    summary: "宿場に残された古い手紙を、記録上の宛先まで届ける。簡単な確認依頼。",
    outcomes: { full: ["成功", "持ち帰り"], partial: ["再配達", "部分成功"], fail: [] }
  },
  {
    id: "quest_wedding_support",
    title: "結婚式の手伝い",
    category: "生活",
    danger: "低",
    area: "町の小さな祝宴会場",
    durationBand: "near_10m",
    recommended: ["世話焼き", "郵便配達人", "豪胆"],
    tags: ["生活", "祝宴", "運搬", "案内", "地域"],
    observationTarget: "なし",
    tensionBase: 15,
    tensionRange: 15,
    summary: "町の小さな結婚式を手伝う。会場設営、料理の運搬、招待客の案内、夜間の見回り、迷子対応を行う。",
    outcomes: { full: ["成功", "感謝"], partial: [], fail: ["小さな失敗"] }
  },
  {
    id: "quest_old_house_cleanup",
    title: "廃屋の片付け",
    category: "生活",
    danger: "低",
    area: "町外れの古い家屋",
    durationBand: "near_1m",
    recommended: ["慎重", "豪胆", "記録"],
    tags: ["生活", "片付け", "記録", "荷運び", "古物"],
    observationTarget: "なし",
    tensionBase: 28,
    tensionRange: 20,
    summary: "町外れの古い家屋を片付ける。壊れた家具、古い手紙、小物、埃をかぶった生活用品を整理する。",
    outcomes: { full: ["成功", "整理完了"], partial: ["一部保留"], fail: [] }
  },
  {
    id: "quest_field_mystery",
    title: "畑を荒らす「なにか」の追い払い",
    category: "戦闘",
    danger: "低",
    area: "村はずれの畑",
    durationBand: "short_30m",
    unlockedBy: "quest_signpost",
    recommended: ["戦士", "慎重", "観察"],
    tags: ["戦闘", "追い払い", "未同定", "畑"],
    observationTarget: "「なにか」",
    tensionBase: 45,
    tensionRange: 15,
    enemyId: "enemy_field_pest",
    battleEffectiveItemIds: ["item_bandage"],
    summary: "畑を荒らす未同定の小さな影を追い払う。討伐ではなく、畑の外へ押し返すことが目的。",
    outcomes: { full: ["追い払い"], partial: ["追い払い中止"], fail: ["追い払い失敗"] }
  },
  {
    id: "quest_barn_bite",
    title: "納屋に巣食う噛みつく「なにか」の討伐",
    category: "戦闘",
    danger: "中",
    area: "古い納屋",
    durationBand: "short_1h",
    unlockedBy: "quest_field_mystery",
    recommended: ["戦士", "豪胆", "観察"],
    tags: ["戦闘", "討伐", "未同定", "納屋"],
    observationTarget: "嚙みつく「なにか」",
    tensionBase: 72,
    tensionRange: 18,
    enemyId: "enemy_barn_biter",
    battleEffectiveItemIds: ["item_bandage"],
    summary: "納屋の奥に巣食い、家畜や人に噛みつく未同定の相手を仕留める。追い払いではなく討伐が必要。",
    outcomes: { full: ["討伐"], partial: ["討伐中止"], fail: ["討伐失敗"] }
  },
  {
    id: "quest_old_bridge_repair",
    title: "古い小橋の応急修理",
    category: "保全",
    danger: "低",
    area: "村はずれの小川",
    durationBand: "short_30m",
    unlockedBy: "quest_evening_market_escort",
    recommended: ["戦士", "慎重", "見習い盾役"],
    tags: ["保全", "修繕", "水辺", "足場", "応急処置", "地域"],
    observationTarget: "なし",
    tensionBase: 30,
    tensionRange: 20,
    summary: "村はずれの小川にかかる古い小橋を応急修理する。板の緩み、手すり、足場を確認し、通行できる状態に戻す。",
    outcomes: { full: ["応急修理", "通行可"], partial: ["一部保留"], fail: [] }
  },
  {
    id: "quest_church_patrol",
    title: "辺境教会周辺の定期巡回",
    category: "保全",
    danger: "低",
    area: "辺境教会の外縁",
    durationBand: "mid_2h",
    unlockedBy: "quest_old_bridge_repair",
    recommended: ["斥候", "慎重", "見習い盾役"],
    tags: ["保全", "巡回", "安全確認", "定期", "地域", "辺境教会", "祈り場"],
    observationTarget: "なし",
    tensionBase: 20,
    tensionRange: 15,
    summary: "辺境教会の周辺を巡回し、道、柵、鐘楼、花壇、礼拝堂外縁に異常がないか確認する。最近、夜明け前に小さな灯りを見たという話がある。",
    outcomes: { full: ["異常なし", "軽微な対処"], partial: ["要再確認", "小さな違和感"], fail: [] }
  },
  {
    id: "quest_herb_delivery",
    title: "薬草包みの納品",
    category: "輸送",
    danger: "低",
    area: "雨待ちの街道",
    durationBand: "short_30m",
    unlockedBy: "quest_wedding_support",
    recommended: ["薬草師", "斥候", "慎重"],
    tags: ["輸送", "配達", "薬草", "街道", "壊れ物", "地域"],
    observationTarget: "なし",
    tensionBase: 28,
    tensionRange: 22,
    summary: "村の調合所から受け取った薬草包みを、街道沿いの診療所へ届ける。濡れや揺れに気をつけながら、指定の時刻までに納品する。",
    outcomes: { full: ["納品完了", "時刻内納品"], partial: ["一部注意"], fail: [] }
  },
  {
    id: "quest_missing_herbalist",
    title: "帰ってこない薬草採りの確認",
    category: "救助",
    danger: "中",
    area: "薄明の森の浅瀬",
    durationBand: "mid_2h",
    unlockedBy: "quest_barn_bite",
    recommended: ["斥候", "薬草師", "慎重"],
    tags: ["救助", "捜索", "薬草", "森", "足跡", "帰還", "地域"],
    observationTarget: "なし",
    tensionBase: 58,
    tensionRange: 28,
    summary: "朝に薬草を採りに出た村人が、夕方になっても戻らない。森の浅い場所を確認し、必要なら保護して連れ帰る。",
    outcomes: { full: ["保護", "発見"], partial: ["痕跡確認"], fail: [] }
  },
  {
    id: "quest_evening_market_escort",
    title: "夕市帰りの親子の付き添い",
    category: "護衛",
    danger: "低",
    area: "夕暮れの街道",
    durationBand: "near_10m",
    recommended: ["見習い盾役", "斥候", "慎重"],
    tags: ["護衛", "付き添い", "夕方", "街道", "親子", "地域", "帰還"],
    observationTarget: "なし",
    tensionBase: 42,
    tensionRange: 25,
    summary: "夕市から帰る親子を、町外れの家まで付き添う。荷物を持ち、暗くなる前に安全な道を選んで帰す。",
    outcomes: { full: ["無事帰宅", "安全確認"], partial: ["遠回り帰宅"], fail: [] }
  },
  {
    id: "quest_caravan_escort",
    title: "街道の外れを行く隊商の護衛",
    category: "護衛",
    danger: "中",
    area: "生活圏の外縁を抜ける街道",
    durationBand: "mid_3h",
    unlockedBy: "quest_barn_bite",
    recommended: ["戦士", "見習い盾役", "斥候"],
    tags: ["護衛", "隊商", "戦闘", "街道", "撤退判断", "掴み"],
    observationTarget: "なし",
    tensionBase: 55,
    tensionRange: 25,
    enemyId: "enemy_road_raiders",
    battleEffectiveItemIds: ["item_bandage"],
    summary: "生活圏の外縁を抜ける隊商を護る。道中で野盗に会敵しうる。強行突破・煙幕での離脱回避・護り切れず撤退の三つに分かれる。",
    // ★ 交戦回避（依頼未達）は現状 full 扱い（登録漏れの再現）。段階④で fail へ移す。
    outcomes: { full: ["護衛成功", "護衛成功（負傷）", "交戦回避（依頼未達）"], partial: ["隊商通過（遅延あり）", "隊商通過（荷の一部損失）"], fail: ["荷を置いて撤退", "護衛失敗"] }
  },
  {
    id: "quest_caravan_search",
    title: "隊商の緊急捜索",
    category: "捜索",
    danger: "中",
    area: "生活圏の外縁を抜ける街道",
    durationBand: "mid_2h",
    recommended: ["斥候"],
    tags: ["捜索", "隊商", "緊急", "護衛失敗"],
    observationTarget: "なし",
    tensionBase: 50,
    tensionRange: 25,
    hidden: true,
    summary: "護り切れなかった隊商を追う緊急の捜索依頼。足跡を読む斥候か、鼻の利く者が要る。",
    outcomes: { full: ["隊商奪還"], partial: ["手がかりのみ"], fail: [] }
  },
  {
    id: "quest_caravan_lastchance",
    title: "最後の手がかり",
    category: "捜索",
    danger: "高",
    area: "生活圏の外縁を抜ける街道",
    durationBand: "mid_3h",
    recommended: ["斥候"],
    tags: ["捜索", "隊商", "最後", "緊急"],
    observationTarget: "なし",
    tensionBase: 60,
    tensionRange: 25,
    hidden: true,
    summary: "手がかりが尽きかけた再捜索。これを逃せば、隊商はもう戻らない。",
    outcomes: { full: [], partial: ["辛くも奪還"], fail: ["隊商喪失"] }
  },
  {
    id: "quest_old_stele_rubbing",
    title: "古い石碑の拓本",
    category: "記録",
    danger: "低",
    area: "旧街道脇の石碑",
    durationBand: "short_30m",
    unlockedBy: "quest_lingering_light",
    recommended: ["斥候", "薬草師", "慎重"],
    tags: ["記録", "石碑", "拓本", "旧街道", "文字", "歴史", "地域"],
    observationTarget: "なし",
    tensionBase: 34,
    tensionRange: 24,
    summary: "旧街道脇に残る古い石碑の文字を、拓本として写し取る。苔や欠けで読みにくいが、無理に削らず、読める範囲を記録する。",
    outcomes: { full: ["拓本完了", "保存優先"], partial: ["一部判読"], fail: [] }
  },
  {
    id: "quest_lingering_light",
    title: "夜道に残る灯りの調査",
    category: "調査",
    danger: "低",
    area: "村はずれの道",
    durationBand: "near_10m",
    recommended: ["慎重", "記録", "観察"],
    tags: ["調査", "夜道", "怪異", "記録"],
    observationTarget: "残る灯り",
    tensionBase: 62,
    tensionRange: 28,
    summary: "夜になると誰も持っていない灯りが見えるという道を調べる。昼は通常の道として確認する。",
    // ★ 確認のみ／調査成功は現状 full 扱い（登録漏れの再現）。段階④で正しい段階へ移す。
    outcomes: { full: ["異常なし", "確認のみ", "調査成功"], partial: [], fail: [] }
  }
];
